name: "Cinexis Remote Access"
description: "Secure remote access and Alexa Smart Home for Home Assistant via Cinexis Cloud. No port forwarding required."
version: "1.7.0"
slug: "cinexis_remote"
init: false
arch:
  - amd64
  - aarch64
  - armv7
image: "ghcr.io/cinexisin/cinexis-remote-access/{arch}"
homeassistant: "2023.1.0"
startup: services
boot: auto
apparmor: true
map:
  - type: share
    read_only: false
options:
  log_level: info
  name_prefix: ""
  admin_email: ""
  admin_otp: ""
schema:
  log_level: list(trace|debug|info|warning|error)
  name_prefix: str
  admin_email: str?
  admin_otp: str?
url: "https://cinexis.cloud"
